image: php:7.4

pipelines:
 branches:
   master:
     - step:
         name: Deploy to production
         deployment: production
         script:
           - apt-get update
           - apt-get -qq install git-ftp
           - git ftp push --user testingUser@testing.lideploy.space --passwd zaq1@WSXcde3 ftp://ftp.lideploy.space